server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/malakgridah9-oss/telecom-config-repo
          default-label: main
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"